#!/usr/bin/env bash
# A  Bash script that displays:
# The content of the current directory
# In a line format
# Where only the part of the name after the dash is displayed

for i in *;
do
	echo "$i" | cut -d'-' -f2
done
